import { ELEMENT_CHOICE_SUBJECT, ELEMENT_CREATE, ELEMENT_INTENDED_DEGREE_PROGRAM, ELEMENT_RESUME, ELEMENT_START } from "../Element/ELEMENT.mjs";

/**
 * @typedef {ELEMENT_CHOICE_SUBJECT | ELEMENT_CREATE | ELEMENT_INTENDED_DEGREE_PROGRAM | ELEMENT_RESUME | ELEMENT_START} PAGE
 */
