stages:
    - build
    - test
    - publish
    - publish-utils

default:
    image: docker:latest
    before_script: |
        DOCKER_IMAGE_TAG=${CI_COMMIT_REF_NAME/main/latest}
        if [ ! -z `command -v docker` ]; then
            echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
            if [ -n "$DOCKER_REGISTRY_USER" ]; then echo -n $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin; fi
        fi
    after_script: |
        if [ ! -z `command -v docker` ]; then
            docker logout $CI_REGISTRY
            if [ -n "$DOCKER_REGISTRY_USER" ]; then docker logout; fi
        fi

build:
    stage: build
    script:
        - docker build . --pull --build-arg COMMIT_SHA=$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
        - docker push $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
    only:
        - branches
        - tags

lint:
    stage: test
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-js-lint:latest
    script:
        - flux-js-lint
    only:
        - branches
        - tags
    allow_failure: true

publish:
    stage: publish
    script:
        - docker pull $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
        - docker tag $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG $DOCKER_REGISTRY_USER/$CI_PROJECT_NAME:$DOCKER_IMAGE_TAG
        - docker push $DOCKER_REGISTRY_USER/$CI_PROJECT_NAME:$DOCKER_IMAGE_TAG
    only:
        - main
        - tags

publish-utils:
    stage: publish-utils
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-publish-utils:latest
    script:
        - publish-utils
    only:
        - main
