import { INDEXDB_IMPLEMENTATION_STORE_NAME } from "./INDEXDB_IMPLEMENTATION_STORE_NAME.mjs";

export const INDEXDB_IMPLEMENTATION_DATABASE_NAME = `studis-selfservice-${INDEXDB_IMPLEMENTATION_STORE_NAME}`;
