export const SETTINGS_INDEXEDDB_IMPLEMENTATION_STORE_NAME = "settings";

export const SETTINGS_INDEXEDDB_IMPLEMENTATION_DATABASE_NAME = `flux-studis-selfservice-${SETTINGS_INDEXEDDB_IMPLEMENTATION_STORE_NAME}`;
