export const SETTINGS_INDEXEDDB_IMPLEMENTATION_STORE_NAME = "settings";

export const SETTINGS_INDEXEDDB_IMPLEMENTATION_DATABASE_NAME = `flux-studis-selfservice-${SETTINGS_INDEXEDDB_IMPLEMENTATION_STORE_NAME}`;

export const SETTINGS_STORAGE_IMPLEMENTATION_KEY_PREFIX = `${SETTINGS_INDEXEDDB_IMPLEMENTATION_DATABASE_NAME}-`;

export const SETTINGS_CACHE_IMPLEMENTATION_CACHE_NAME = SETTINGS_INDEXEDDB_IMPLEMENTATION_DATABASE_NAME;
